from sqlalchemy import Column, String, LargeBinary, DateTime, ForeignKey, Integer
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from . import __init__  # keep package marker import happy
from services.database import Base

class Mapping(Base):
    __tablename__ = "mappings"
    token = Column(String(64), primary_key=True)
    value_nonce = Column(LargeBinary(12), nullable=False)
    value_ciphertext = Column(LargeBinary, nullable=False)
    value_type = Column(String(32), nullable=False)
    call_id = Column(String(64), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    last_used_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)


class Call(Base):
    """
    Tracks individual phone calls from start to finish.
    Each row represents one phone conversation.
    """
    __tablename__ = "calls"
    
    # ============================================================================
    # PRIMARY IDENTIFIERS
    # ============================================================================
    
    call_sid = Column(String(64), primary_key=True)
    # Twilio's unique identifier for this call (e.g., "CA1234567890abcdef")
    # This comes from Twilio and is their system of record ID
    # Primary key because Twilio guarantees uniqueness
    
    call_id = Column(String(64), nullable=False, unique=True, index=True)
    # Our internal tracking ID (e.g., "CALL_20251010_001")
    # We generate this for our own correlation across logs, tokens, etc.
    # Indexed because we'll frequently query by this ID
    # Unique constraint ensures we don't accidentally create duplicates
    
    # ============================================================================
    # CALLER INFORMATION (Tokenized for HIPAA)
    # ============================================================================
    
    caller_phone_token = Column(String(64), nullable=True)
    # The tokenized phone number of the caller (e.g., "PHONE_ABC123")
    # Nullable because: 
    #   - Caller ID might be blocked/unavailable
    #   - Call might fail before we can tokenize
    # References a token in the Mapping table where actual phone is encrypted
    
    # ============================================================================
    # CALL STATUS TRACKING
    # ============================================================================
    
    status = Column(String(20), default="initiated", nullable=False)
    # Current state of the call. Possible values:
    #   - "initiated": Call received, setting up
    #   - "active": Currently in conversation
    #   - "completed": Call ended normally
    #   - "failed": Technical failure (network, service error)
    #   - "abandoned": Caller hung up before completion
    # Default is "initiated" when call first comes in
    
    # ============================================================================
    # TIMESTAMPS
    # ============================================================================
    
    started_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    # When the call was first received
    # Uses server_default so PostgreSQL automatically sets this
    # Timezone-aware for proper handling across regions
    # Never null - every call has a start time
    
    ended_at = Column(DateTime(timezone=True), nullable=True)
    # When the call ended (any reason: completion, failure, hangup)
    # Nullable because active calls haven't ended yet
    # We'll update this field when call terminates

    # ============================================================================
    # RELATIONSHIPS
    # ============================================================================
    
    # Optional link to patient (if caller is identified as existing patient)
    patient_id = Column(String(64), ForeignKey("patients.patient_id"), nullable=True)
    patient = relationship("Patient", back_populates="calls")

class Patient(Base):
    """
    Patient records with tokenized PHI for HIPAA compliance.
    All personally identifiable information is stored as tokens.
    """
    __tablename__ = "patients"
    
    # ============================================================================
    # PRIMARY IDENTIFIERS
    # ============================================================================
    
    patient_id = Column(String(64), primary_key=True)
    # Our internal patient ID (e.g., "PATIENT_20250110_001")
    # Generated by our system for internal tracking
    
    # ============================================================================
    # TOKENIZED PHI (All sensitive data is tokenized)
    # ============================================================================
    
    name_token = Column(String(64), nullable=True)
    # Tokenized full name (e.g., "PATIENT_ABC123")
    # References Mapping table where actual name is encrypted
    
    phone_token = Column(String(64), nullable=True)
    # Tokenized primary phone number (e.g., "PHONE_XYZ789")
    # References Mapping table where actual phone is encrypted
    
    email_token = Column(String(64), nullable=True)
    # Tokenized email address (e.g., "EMAIL_DEF456")
    # References Mapping table where actual email is encrypted
    
    dob_token = Column(String(64), nullable=True)
    # Tokenized date of birth (e.g., "DATE_GHI789")
    # References Mapping table where actual DOB is encrypted
    
    # ============================================================================
    # INSURANCE (Most patients have one primary insurance)
    # ============================================================================
    
    insurance_provider_token = Column(String(64), nullable=True)
    # Tokenized insurance provider name (e.g., "INSURANCE_ABC123")
    
    insurance_member_id_token = Column(String(64), nullable=True)
    # Tokenized insurance member ID (e.g., "MEMBER_XYZ789")
    
    insurance_plan_type = Column(String(50), nullable=True)  # HMO, PPO, EPO, etc.
    
    # ============================================================================
    # TIMESTAMPS
    # ============================================================================
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # ============================================================================
    # RELATIONSHIPS
    # ============================================================================
    
    # One patient can have many calls
    calls = relationship("Call", back_populates="patient")
    # One patient can have many appointments
    appointments = relationship("Appointment", back_populates="patient")

class Appointment(Base):
    """
    Medical appointments linking patients to calls and providers.
    """
    __tablename__ = "appointments"
    
    appointment_id = Column(String(64), primary_key=True)
    # Our internal appointment ID (e.g., "APPT_20250110_001")
    
    # ============================================================================
    # RELATIONSHIPS TO OTHER ENTITIES
    # ============================================================================
    
    patient_id = Column(String(64), ForeignKey("patients.patient_id"), nullable=False)
    provider_id = Column(String(64), ForeignKey("providers.provider_id"), nullable=True)
    call_id = Column(String(64), ForeignKey("calls.call_id"), nullable=True)
    # Optional link to the call that created this appointment
    
    # ============================================================================
    # APPOINTMENT TIMING (Non-PHI for scheduling logic)
    # ============================================================================
    
    appointment_date = Column(DateTime(timezone=True), nullable=True)
    # Actual appointment date and time (non-PHI for scheduling)
    
    start_time = Column(DateTime(timezone=True), nullable=True)
    # Appointment start time
    
    end_time = Column(DateTime(timezone=True), nullable=True)
    # Appointment end time (calculated from start_time + duration_minutes)
    
    # ============================================================================
    # TOKENIZED APPOINTMENT DATA
    # ============================================================================
    
    reason_token = Column(String(64), nullable=True)
    # Tokenized appointment reason/chief complaint
    
    notes_token = Column(String(64), nullable=True)
    # Tokenized appointment notes
    
    # ============================================================================
    # NON-PHI APPOINTMENT DATA
    # ============================================================================
    
    appointment_type = Column(String(50), nullable=True)  # consultation, follow-up, procedure, etc.
    duration_minutes = Column(Integer, default=30, nullable=False)
    status = Column(String(20), default="scheduled", nullable=False)
    # scheduled, confirmed, completed, cancelled, no_show
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # ============================================================================
    # RELATIONSHIPS
    # ============================================================================
    
    patient = relationship("Patient", back_populates="appointments")
    provider = relationship("Provider", back_populates="appointments")
    call = relationship("Call")


class AppointmentBlock(Base):
    """
    Manages consistent appointment time blocks for providers.
    Ensures appointments are scheduled in standard time slots.
    """
    __tablename__ = "appointment_blocks"
    
    block_id = Column(String(64), primary_key=True)
    # Our internal block ID (e.g., "BLOCK_20250110_001")
    
    provider_id = Column(String(64), ForeignKey("providers.provider_id"), nullable=False)
    
    # ============================================================================
    # TIME BLOCK DEFINITION
    # ============================================================================
    
    block_date = Column(DateTime(timezone=True), nullable=False)
    # Date for this time block (e.g., 2025-01-10)
    
    start_time = Column(DateTime(timezone=True), nullable=False)
    # Block start time (e.g., 2025-01-10 09:00:00)
    
    end_time = Column(DateTime(timezone=True), nullable=False)
    # Block end time (e.g., 2025-01-10 17:00:00)
    
    # ============================================================================
    # BLOCK CONFIGURATION
    # ============================================================================
    
    slot_duration_minutes = Column(Integer, default=30, nullable=False)
    # Duration of each appointment slot (15, 30, 45, 60 minutes)
    
    break_duration_minutes = Column(Integer, default=0, nullable=False)
    # Break time between appointments
    
    max_appointments = Column(Integer, nullable=True)
    # Maximum number of appointments in this block
    
    # ============================================================================
    # BLOCK STATUS
    # ============================================================================
    
    is_available = Column(String(10), default="yes", nullable=False)
    # yes, no, partially_booked
    
    status = Column(String(20), default="active", nullable=False)
    # active, cancelled, completed
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # ============================================================================
    # RELATIONSHIPS
    # ============================================================================
    
    provider = relationship("Provider", back_populates="appointment_blocks")
    # One block belongs to one provider


class Provider(Base):
    """
    Healthcare providers (doctors, nurses, staff) that the AI can schedule with.
    """
    __tablename__ = "providers"
    
    provider_id = Column(String(64), primary_key=True)
    # Our internal provider ID (e.g., "PROVIDER_20250110_001")
    
    # ============================================================================
    # TOKENIZED PROVIDER INFO
    # ============================================================================
    
    name_token = Column(String(64), nullable=False)
    # Tokenized provider name (e.g., "PROVIDER_ABC123")
    
    # ============================================================================
    # NON-PHI PROVIDER DATA
    # ============================================================================
    
    title = Column(String(50), nullable=True)  # Dr., Nurse, etc.
    specialty = Column(String(100), nullable=True)  # Cardiology, General Practice, etc.
    license_number = Column(String(50), nullable=True)  # Medical license number
    npi_number = Column(String(20), nullable=True)  # National Provider Identifier
    
    # Availability for AI scheduling
    is_available = Column(String(10), default="yes", nullable=False)  # yes, no, limited
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # ============================================================================
    # RELATIONSHIPS
    # ============================================================================
    
    # One provider can have many appointments
    appointments = relationship("Appointment", back_populates="provider")
    # One provider can have many appointment blocks
    appointment_blocks = relationship("AppointmentBlock", back_populates="provider")


class CallNotes(Base):
    """
    AI-generated summaries and notes from call conversations.
    Tracks patient call history with datetime for when same patient calls multiple times.
    """
    __tablename__ = "call_notes"
    
    notes_id = Column(String(64), primary_key=True)
    # Our internal notes ID (e.g., "NOTES_20250110_001")
    
    call_id = Column(String(64), ForeignKey("calls.call_id"), nullable=False)
    patient_id = Column(String(64), ForeignKey("patients.patient_id"), nullable=True)
    # Link to patient for tracking call history
    
    # ============================================================================
    # TOKENIZED CALL CONTENT
    # ============================================================================
    
    summary_token = Column(String(64), nullable=True)
    # Tokenized AI-generated call summary
    
    key_points_token = Column(String(64), nullable=True)
    # Tokenized key discussion points from the call
    
    action_items_token = Column(String(64), nullable=True)
    # Tokenized follow-up actions needed
    
    # ============================================================================
    # NON-PHI CALL ANALYSIS
    # ============================================================================
    
    sentiment_score = Column(String(20), nullable=True)  # positive, negative, neutral
    urgency_level = Column(String(20), nullable=True)  # low, medium, high, emergency
    call_duration_seconds = Column(Integer, nullable=True)
    ai_confidence_score = Column(String(20), nullable=True)  # low, medium, high
    
    # Structured data extracted by AI
    symptoms_detected = Column(String(500), nullable=True)  # Comma-separated symptoms
    medications_mentioned = Column(String(500), nullable=True)  # Comma-separated medications
    concerns_raised = Column(String(500), nullable=True)  # Comma-separated concerns
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # ============================================================================
    # RELATIONSHIPS
    # ============================================================================
    
    call = relationship("Call")
    patient = relationship("Patient")


class AuditLog(Base):
    """
    Audit trail for all PHI access and system changes.
    Essential for HIPAA compliance and security monitoring.
    """
    __tablename__ = "audit_logs"
    
    log_id = Column(String(64), primary_key=True)
    # Our internal log ID (e.g., "AUDIT_20250110_001")
    
    # ============================================================================
    # AUDIT TRAIL INFORMATION
    # ============================================================================
    
    user_id = Column(String(64), nullable=True)
    # Who performed the action (system, admin, api_key, etc.)
    
    action_type = Column(String(50), nullable=False)
    # create, read, update, delete, tokenize, hydrate, access_phi
    
    table_name = Column(String(50), nullable=True)
    # Which table was affected (patients, calls, mappings, etc.)
    
    record_id = Column(String(64), nullable=True)
    # Which specific record was affected
    
    # ============================================================================
    # REQUEST CONTEXT
    # ============================================================================
    
    ip_address = Column(String(45), nullable=True)  # IPv4 or IPv6
    user_agent = Column(String(500), nullable=True)
    request_id = Column(String(64), nullable=True)  # For tracing requests
    
    # ============================================================================
    # DETAILS
    # ============================================================================
    
    details = Column(String(1000), nullable=True)
    # Additional context about what happened
    
    success = Column(String(10), default="yes", nullable=False)  # yes, no
    # Whether the action was successful
    
    # ============================================================================
    # TIMESTAMPS
    # ============================================================================
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    # When the action occurred


class CallQueue(Base):
    """
    Manages call routing, priority, and queue management.
    Routes calls to appropriate AI models or human agents.
    """
    __tablename__ = "call_queue"
    
    queue_id = Column(String(64), primary_key=True)
    # Our internal queue ID (e.g., "QUEUE_20250110_001")
    
    call_id = Column(String(64), ForeignKey("calls.call_id"), nullable=False)
    
    # ============================================================================
    # QUEUE MANAGEMENT
    # ============================================================================
    
    priority_level = Column(String(20), default="normal", nullable=False)
    # normal, emergency (based on call arrival and caller statements)
    
    queue_status = Column(String(20), default="waiting", nullable=False)
    # waiting, processing, completed, failed, transferred_to_human
    
    # ============================================================================
    # EMERGENCY ROUTING
    # ============================================================================
    
    is_emergency = Column(String(10), default="no", nullable=False)
    # yes, no (determined by AI analysis of caller statements)
    
    emergency_reason = Column(String(200), nullable=True)
    # What the caller said that indicated emergency (tokenized)
    
    transferred_to_human = Column(String(10), default="no", nullable=False)
    # yes, no (if emergency, automatically route to human agent)
    
    assigned_human_agent = Column(String(64), nullable=True)
    # Which human agent at the clinic is handling the emergency call
    
    # ============================================================================
    # PROCESSING TIMELINE
    # ============================================================================
    
    ai_processing_started_at = Column(DateTime(timezone=True), nullable=True)
    # When AI started processing the call
    
    ai_processing_completed_at = Column(DateTime(timezone=True), nullable=True)
    # When AI finished processing (before potential human transfer)
    
    human_transfer_at = Column(DateTime(timezone=True), nullable=True)
    # When call was transferred to human agent (if emergency)
    
    # ============================================================================
    # TIMESTAMPS
    # ============================================================================
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # ============================================================================
    # RELATIONSHIPS
    # ============================================================================
    
    call = relationship("Call")


class SystemConfig(Base):
    """
    System configuration settings and AI model configurations.
    Stores emergency keywords, clinic hours, AI model versions, etc.
    """
    __tablename__ = "system_config"
    
    config_id = Column(String(64), primary_key=True)
    # Our internal config ID (e.g., "CONFIG_20250110_001")
    
    # ============================================================================
    # CONFIGURATION DATA
    # ============================================================================
    
    config_key = Column(String(100), nullable=False, unique=True)
    # Configuration key (e.g., "emergency_keywords", "clinic_hours", "ai_model_version")
    
    config_value = Column(String(1000), nullable=False)
    # Configuration value (JSON string or simple value)
    
    config_type = Column(String(20), default="string", nullable=False)
    # string, json, number, boolean
    
    # ============================================================================
    # CATEGORIZATION
    # ============================================================================
    
    category = Column(String(50), nullable=True)
    # emergency, ai_models, clinic_settings, security, etc.
    
    description = Column(String(500), nullable=True)
    # Human-readable description of what this config does
    
    # ============================================================================
    # ACCESS CONTROL
    # ============================================================================
    
    is_sensitive = Column(String(10), default="no", nullable=False)
    # yes, no (whether this config contains sensitive data)
    
    requires_restart = Column(String(10), default="no", nullable=False)
    # yes, no (whether changing this config requires system restart)
    
    # ============================================================================
    # AUDIT TRAIL
    # ============================================================================
    
    updated_by = Column(String(64), nullable=True)
    # Who last updated this configuration
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)