"""Add reminder system tables

Revision ID: 0005
Revises: 0004
Create Date: 2025-01-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('reminder_id', sa.String(64), nullable=False),
    sa.Column('appointment_id', sa.String(64), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_type', sa.String(20), server_default='appointment_reminder', nullable=False),
    sa.Column('status', sa.String(20), server_default='scheduled', nullable=False),
    sa.Column('reminder_call_id', sa.String(64), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('next_retry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('call_outcome', sa.String(50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.String(10), server_default='no', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(64), nullable=True),
    sa.Column('deletion_reason', sa.String(200), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id')
    )
    op.create_index('idx_reminders_appointment', 'reminders', ['appointment_id'], unique=False)
    op.create_index('idx_reminders_retry', 'reminders', ['next_retry_time', 'status'], unique=False)
    op.create_index('idx_reminders_scheduled', 'reminders', ['scheduled_time', 'status'], unique=False)
    op.create_index('idx_reminders_status', 'reminders', ['status', 'scheduled_time'], unique=False)
    op.create_table('reminder_logs',
    sa.Column('log_id', sa.String(64), nullable=False),
    sa.Column('reminder_id', sa.String(64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('call_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('call_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_status', sa.String(20), nullable=False),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('call_outcome', sa.String(50), nullable=True),
    sa.Column('error_code', sa.String(50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('caller_id', sa.String(20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(10), server_default='no', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(64), nullable=True),
    sa.Column('deletion_reason', sa.String(200), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.reminder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_reminder_logs_outcome', 'reminder_logs', ['call_outcome', 'call_started_at'], unique=False)
    op.create_index('idx_reminder_logs_reminder', 'reminder_logs', ['reminder_id', 'attempt_number'], unique=False)
    op.create_index('idx_reminder_logs_status', 'reminder_logs', ['call_status', 'call_started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reminder_logs_status', table_name='reminder_logs')
    op.drop_index('idx_reminder_logs_reminder', table_name='reminder_logs')
    op.drop_index('idx_reminder_logs_outcome', table_name='reminder_logs')
    op.drop_table('reminder_logs')
    op.drop_index('idx_reminders_status', table_name='reminders')
    op.drop_index('idx_reminders_scheduled', table_name='reminders')
    op.drop_index('idx_reminders_retry', table_name='reminders')
    op.drop_index('idx_reminders_appointment', table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
