"""Add address_token and google_event_id fields

Revision ID: bab5a84829b2
Revises: 0005
Create Date: 2025-10-15 22:52:37.021919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab5a84829b2'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('success', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_audit_logs_action_date', 'audit_logs', ['action_type', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_table_date', 'audit_logs', ['table_name', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_user_date', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('caller_types',
    sa.Column('caller_type_id', sa.String(length=64), nullable=False),
    sa.Column('caller_type_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('default_routing_strategy', sa.String(length=50), nullable=False),
    sa.Column('default_overload_policy', sa.String(length=50), nullable=False),
    sa.Column('max_queue_size', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('caller_type_id'),
    sa.UniqueConstraint('caller_type_name')
    )
    op.create_index('idx_caller_types_active', 'caller_types', ['caller_type_id'], unique=False, postgresql_where=sa.text("is_deleted = 'no' AND is_active = true"))
    op.create_index('idx_caller_types_priority', 'caller_types', ['priority_level'], unique=False)
    op.create_table('clinics',
    sa.Column('clinic_id', sa.String(length=64), nullable=False),
    sa.Column('clinic_name', sa.String(length=200), nullable=False),
    sa.Column('clinic_name_token', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email_token', sa.String(length=64), nullable=True),
    sa.Column('address_token', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('default_language', sa.String(length=5), nullable=False),
    sa.Column('supported_languages', sa.String(length=20), nullable=False),
    sa.Column('ehr_system', sa.String(length=20), nullable=False),
    sa.Column('ehr_api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('ehr_credentials_vault_key', sa.String(length=100), nullable=True),
    sa.Column('ehr_enabled', sa.String(length=10), nullable=False),
    sa.Column('fallback_system', sa.String(length=20), nullable=False),
    sa.Column('fallback_credentials_vault_key', sa.String(length=100), nullable=True),
    sa.Column('max_concurrent_calls', sa.Integer(), nullable=False),
    sa.Column('queue_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('overload_action', sa.String(length=20), nullable=False),
    sa.Column('staff_forward_number', sa.String(length=20), nullable=True),
    sa.Column('reminders_enabled', sa.String(length=10), nullable=False),
    sa.Column('reminder_hours_before', sa.Integer(), nullable=False),
    sa.Column('reminder_retry_minutes', sa.Integer(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_call_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('clinic_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('mappings',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('value_nonce', sa.LargeBinary(length=12), nullable=False),
    sa.Column('value_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('name_token', sa.String(length=64), nullable=True),
    sa.Column('phone_token', sa.String(length=64), nullable=True),
    sa.Column('email_token', sa.String(length=64), nullable=True),
    sa.Column('dob_token', sa.String(length=64), nullable=True),
    sa.Column('address_token', sa.String(length=64), nullable=True),
    sa.Column('insurance_provider_token', sa.String(length=64), nullable=True),
    sa.Column('insurance_member_id_token', sa.String(length=64), nullable=True),
    sa.Column('insurance_plan_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index('idx_patients_address_token', 'patients', ['address_token'], unique=False)
    op.create_index('idx_patients_email_token', 'patients', ['email_token'], unique=False)
    op.create_index('idx_patients_phone_token', 'patients', ['phone_token'], unique=False)
    op.create_table('providers',
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('name_token', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('npi_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('system_config',
    sa.Column('config_id', sa.String(length=64), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=1000), nullable=False),
    sa.Column('config_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_sensitive', sa.String(length=10), nullable=False),
    sa.Column('requires_restart', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('appointment_blocks',
    sa.Column('block_id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('block_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_appointments', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('call_queues',
    sa.Column('queue_id', sa.String(length=64), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=False),
    sa.Column('caller_type_id', sa.String(length=64), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('max_queue_size', sa.Integer(), nullable=False),
    sa.Column('current_size', sa.Integer(), nullable=False),
    sa.Column('average_wait_time', sa.Float(), nullable=False),
    sa.Column('queue_config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['caller_type_id'], ['caller_types.caller_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_index('idx_call_queues_active', 'call_queues', ['queue_id'], unique=False, postgresql_where=sa.text("is_deleted = 'no' AND is_active = true"))
    op.create_table('clinic_licenses',
    sa.Column('license_id', sa.String(length=64), nullable=False),
    sa.Column('clinic_id', sa.String(length=64), nullable=False),
    sa.Column('license_status', sa.String(length=20), nullable=False),
    sa.Column('license_token', sa.String(length=256), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('max_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('max_concurrent_calls', sa.Integer(), nullable=False),
    sa.Column('max_call_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_providers', sa.Integer(), nullable=True),
    sa.Column('feature_reminders', sa.String(length=10), nullable=False),
    sa.Column('feature_analytics', sa.String(length=10), nullable=False),
    sa.Column('feature_api_access', sa.String(length=10), nullable=False),
    sa.Column('feature_priority_support', sa.String(length=10), nullable=False),
    sa.Column('current_month_calls', sa.Integer(), nullable=False),
    sa.Column('current_month_minutes', sa.Integer(), nullable=False),
    sa.Column('current_concurrent_calls', sa.Integer(), nullable=False),
    sa.Column('usage_percentage', sa.Float(), nullable=False),
    sa.Column('auto_upgrade_threshold', sa.Float(), nullable=False),
    sa.Column('auto_upgrade_offered', sa.String(length=10), nullable=False),
    sa.Column('auto_upgrade_offered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('grace_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_cycle_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_cycle_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monthly_fee_usd', sa.Float(), nullable=False),
    sa.Column('overage_rate_per_call_usd', sa.Float(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspension_reason', sa.String(length=100), nullable=True),
    sa.Column('data_retention_days', sa.Integer(), nullable=False),
    sa.Column('reactivation_count', sa.Integer(), nullable=False),
    sa.Column('last_reactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.clinic_id'], ),
    sa.PrimaryKeyConstraint('license_id')
    )
    op.create_index('idx_license_billing_cycle', 'clinic_licenses', ['clinic_id', 'billing_cycle_start'], unique=False)
    op.create_index('idx_license_current_usage', 'clinic_licenses', ['clinic_id', 'current_month_calls'], unique=False)
    op.create_index('idx_license_status', 'clinic_licenses', ['license_status', 'tier'], unique=False)
    op.create_index(op.f('ix_clinic_licenses_clinic_id'), 'clinic_licenses', ['clinic_id'], unique=True)
    op.create_table('clinic_usage',
    sa.Column('usage_id', sa.String(length=64), nullable=False),
    sa.Column('clinic_id', sa.String(length=64), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('total_call_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_calls', sa.Integer(), nullable=False),
    sa.Column('failed_calls', sa.Integer(), nullable=False),
    sa.Column('abandoned_calls', sa.Integer(), nullable=False),
    sa.Column('forwarded_calls', sa.Integer(), nullable=False),
    sa.Column('calls_english', sa.Integer(), nullable=False),
    sa.Column('calls_spanish', sa.Integer(), nullable=False),
    sa.Column('total_llm_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('total_llm_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_llm_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_stt_minutes', sa.Integer(), nullable=False),
    sa.Column('total_stt_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_tts_characters', sa.Integer(), nullable=False),
    sa.Column('total_tts_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_twilio_minutes', sa.Integer(), nullable=False),
    sa.Column('total_twilio_cost_usd', sa.Float(), nullable=False),
    sa.Column('reminder_calls_sent', sa.Integer(), nullable=False),
    sa.Column('reminder_calls_answered', sa.Integer(), nullable=False),
    sa.Column('reminder_calls_cost_usd', sa.Float(), nullable=False),
    sa.Column('appointments_scheduled', sa.Integer(), nullable=False),
    sa.Column('appointments_cancelled', sa.Integer(), nullable=False),
    sa.Column('appointments_confirmed', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('subscription_fee_usd', sa.Float(), nullable=False),
    sa.Column('overage_fee_usd', sa.Float(), nullable=False),
    sa.Column('total_billable_usd', sa.Float(), nullable=False),
    sa.Column('invoice_generated', sa.String(length=10), nullable=False),
    sa.Column('invoice_id', sa.String(length=64), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.clinic_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index('idx_clinic_usage_current', 'clinic_usage', ['clinic_id', 'billing_period_start', 'invoice_generated'], unique=False)
    op.create_index('idx_clinic_usage_period', 'clinic_usage', ['clinic_id', 'billing_period_start'], unique=False)
    op.create_index(op.f('ix_clinic_usage_billing_period_start'), 'clinic_usage', ['billing_period_start'], unique=False)
    op.create_index(op.f('ix_clinic_usage_clinic_id'), 'clinic_usage', ['clinic_id'], unique=False)
    op.create_table('google_calendar_credentials',
    sa.Column('credential_id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('access_token_nonce', sa.LargeBinary(length=12), nullable=False),
    sa.Column('access_token_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_nonce', sa.LargeBinary(length=12), nullable=True),
    sa.Column('refresh_token_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.PrimaryKeyConstraint('credential_id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_index('idx_credentials_active', 'google_calendar_credentials', ['is_active', 'last_used_at'], unique=False)
    op.create_index('idx_credentials_expires', 'google_calendar_credentials', ['token_expires_at'], unique=False)
    op.create_index('idx_provider_credentials', 'google_calendar_credentials', ['provider_id'], unique=False)
    op.create_table('provider_capacities',
    sa.Column('capacity_id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('max_concurrent_calls', sa.Integer(), nullable=False),
    sa.Column('current_calls', sa.Integer(), nullable=False),
    sa.Column('available_capacity', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('specializations', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capacity_id')
    )
    op.create_index('idx_provider_capacities_available', 'provider_capacities', ['is_available', 'available_capacity'], unique=False)
    op.create_index('idx_provider_capacities_provider', 'provider_capacities', ['provider_id'], unique=False)
    op.create_table('routing_rules',
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('caller_type_id', sa.String(length=64), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('routing_strategy', sa.String(length=50), nullable=False),
    sa.Column('overload_policy', sa.String(length=50), nullable=False),
    sa.Column('max_queue_size', sa.Integer(), nullable=False),
    sa.Column('target_providers', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['caller_type_id'], ['caller_types.caller_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index('idx_routing_rules_active', 'routing_rules', ['rule_id'], unique=False, postgresql_where=sa.text("is_deleted = 'no' AND is_enabled = true"))
    op.create_index('idx_routing_rules_caller_type', 'routing_rules', ['caller_type_id', 'priority_level'], unique=False)
    op.create_table('calls',
    sa.Column('call_sid', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('caller_phone_token', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_caller_type', sa.String(length=50), nullable=True),
    sa.Column('caller_type_confidence', sa.Float(), nullable=True),
    sa.Column('routing_rule_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_provider_id', sa.String(length=64), nullable=True),
    sa.Column('queue_id', sa.String(length=64), nullable=True),
    sa.Column('routing_metadata', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['assigned_provider_id'], ['providers.provider_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['call_queues.queue_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routing_rule_id'], ['routing_rules.rule_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('call_sid')
    )
    op.create_index('idx_calls_patient_date', 'calls', ['patient_id', 'started_at'], unique=False)
    op.create_index('idx_calls_phone_token', 'calls', ['caller_phone_token'], unique=False)
    op.create_index('idx_calls_status_date', 'calls', ['status', 'started_at'], unique=False)
    op.create_index(op.f('ix_calls_call_id'), 'calls', ['call_id'], unique=True)
    op.create_table('appointments',
    sa.Column('appointment_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('call_id', sa.String(length=64), nullable=True),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_token', sa.String(length=64), nullable=True),
    sa.Column('notes_token', sa.String(length=64), nullable=True),
    sa.Column('appointment_type', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('call_notes',
    sa.Column('notes_id', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=True),
    sa.Column('summary_token', sa.String(length=64), nullable=True),
    sa.Column('key_points_token', sa.String(length=64), nullable=True),
    sa.Column('action_items_token', sa.String(length=64), nullable=True),
    sa.Column('sentiment_score', sa.String(length=20), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ai_confidence_score', sa.String(length=20), nullable=True),
    sa.Column('symptoms_detected', sa.String(length=500), nullable=True),
    sa.Column('medications_mentioned', sa.String(length=500), nullable=True),
    sa.Column('concerns_raised', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('notes_id')
    )
    op.create_table('call_queue',
    sa.Column('queue_id', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.Column('queue_status', sa.String(length=20), nullable=False),
    sa.Column('is_emergency', sa.String(length=10), nullable=False),
    sa.Column('emergency_reason', sa.String(length=200), nullable=True),
    sa.Column('transferred_to_human', sa.String(length=10), nullable=False),
    sa.Column('assigned_human_agent', sa.String(length=64), nullable=True),
    sa.Column('ai_processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('human_transfer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_table('caller_detection_logs',
    sa.Column('detection_id', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('caller_phone_token', sa.String(length=64), nullable=True),
    sa.Column('detected_caller_type', sa.String(length=50), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('detection_data', sa.Text(), nullable=True),
    sa.Column('detection_result', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detection_id')
    )
    op.create_index('idx_caller_detection_logs_call', 'caller_detection_logs', ['call_id'], unique=False)
    op.create_index('idx_caller_detection_logs_phone', 'caller_detection_logs', ['caller_phone_token'], unique=False)
    op.create_index('idx_caller_detection_logs_type', 'caller_detection_logs', ['detected_caller_type'], unique=False)
    op.create_table('queued_calls',
    sa.Column('queued_call_id', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('queue_id', sa.String(length=64), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estimated_wait_time', sa.Float(), nullable=True),
    sa.Column('assigned_provider_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['assigned_provider_id'], ['providers.provider_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['call_queues.queue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queued_call_id')
    )
    op.create_index('idx_queued_calls_call', 'queued_calls', ['call_id'], unique=False)
    op.create_index('idx_queued_calls_queue', 'queued_calls', ['queue_id', 'priority_score'], unique=False)
    op.create_index('idx_queued_calls_status', 'queued_calls', ['status', 'queued_at'], unique=False)
    op.create_table('appointment_slots',
    sa.Column('slot_id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('slot_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_booked', sa.String(length=10), nullable=False),
    sa.Column('booked_by_appointment_id', sa.String(length=64), nullable=True),
    sa.Column('held_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('held_by_call_sid', sa.String(length=64), nullable=True),
    sa.Column('clinic_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booked_by_appointment_id'], ['appointments.appointment_id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.clinic_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.PrimaryKeyConstraint('slot_id'),
    sa.UniqueConstraint('provider_id', 'slot_datetime', name='unique_provider_slot')
    )
    op.create_index('idx_appointment_slots_available', 'appointment_slots', ['clinic_id', 'slot_datetime', 'is_booked'], unique=False)
    op.create_index('idx_appointment_slots_clinic_datetime', 'appointment_slots', ['clinic_id', 'slot_datetime'], unique=False)
    op.create_index('idx_appointment_slots_provider_datetime', 'appointment_slots', ['provider_id', 'slot_datetime'], unique=False)
    op.create_index(op.f('ix_appointment_slots_clinic_id'), 'appointment_slots', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointment_slots_provider_id'), 'appointment_slots', ['provider_id'], unique=False)
    op.create_index(op.f('ix_appointment_slots_slot_datetime'), 'appointment_slots', ['slot_datetime'], unique=False)
    op.create_table('reminders',
    sa.Column('reminder_id', sa.String(length=64), nullable=False),
    sa.Column('appointment_id', sa.String(length=64), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reminder_call_id', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('call_outcome', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id')
    )
    op.create_index('idx_reminders_appointment', 'reminders', ['appointment_id'], unique=False)
    op.create_index('idx_reminders_retry', 'reminders', ['next_retry_time', 'status'], unique=False)
    op.create_index('idx_reminders_scheduled', 'reminders', ['scheduled_time', 'status'], unique=False)
    op.create_index('idx_reminders_status', 'reminders', ['status', 'scheduled_time'], unique=False)
    op.create_table('reminder_logs',
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('reminder_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('call_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('call_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_status', sa.String(length=20), nullable=False),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('call_outcome', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('caller_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deletion_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.reminder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_reminder_logs_outcome', 'reminder_logs', ['call_outcome', 'call_started_at'], unique=False)
    op.create_index('idx_reminder_logs_reminder', 'reminder_logs', ['reminder_id', 'attempt_number'], unique=False)
    op.create_index('idx_reminder_logs_status', 'reminder_logs', ['call_status', 'call_started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reminder_logs_status', table_name='reminder_logs')
    op.drop_index('idx_reminder_logs_reminder', table_name='reminder_logs')
    op.drop_index('idx_reminder_logs_outcome', table_name='reminder_logs')
    op.drop_table('reminder_logs')
    op.drop_index('idx_reminders_status', table_name='reminders')
    op.drop_index('idx_reminders_scheduled', table_name='reminders')
    op.drop_index('idx_reminders_retry', table_name='reminders')
    op.drop_index('idx_reminders_appointment', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_appointment_slots_slot_datetime'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_provider_id'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_clinic_id'), table_name='appointment_slots')
    op.drop_index('idx_appointment_slots_provider_datetime', table_name='appointment_slots')
    op.drop_index('idx_appointment_slots_clinic_datetime', table_name='appointment_slots')
    op.drop_index('idx_appointment_slots_available', table_name='appointment_slots')
    op.drop_table('appointment_slots')
    op.drop_index('idx_queued_calls_status', table_name='queued_calls')
    op.drop_index('idx_queued_calls_queue', table_name='queued_calls')
    op.drop_index('idx_queued_calls_call', table_name='queued_calls')
    op.drop_table('queued_calls')
    op.drop_index('idx_caller_detection_logs_type', table_name='caller_detection_logs')
    op.drop_index('idx_caller_detection_logs_phone', table_name='caller_detection_logs')
    op.drop_index('idx_caller_detection_logs_call', table_name='caller_detection_logs')
    op.drop_table('caller_detection_logs')
    op.drop_table('call_queue')
    op.drop_table('call_notes')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_calls_call_id'), table_name='calls')
    op.drop_index('idx_calls_status_date', table_name='calls')
    op.drop_index('idx_calls_phone_token', table_name='calls')
    op.drop_index('idx_calls_patient_date', table_name='calls')
    op.drop_table('calls')
    op.drop_index('idx_routing_rules_caller_type', table_name='routing_rules')
    op.drop_index('idx_routing_rules_active', table_name='routing_rules', postgresql_where=sa.text("is_deleted = 'no' AND is_enabled = true"))
    op.drop_table('routing_rules')
    op.drop_index('idx_provider_capacities_provider', table_name='provider_capacities')
    op.drop_index('idx_provider_capacities_available', table_name='provider_capacities')
    op.drop_table('provider_capacities')
    op.drop_index('idx_provider_credentials', table_name='google_calendar_credentials')
    op.drop_index('idx_credentials_expires', table_name='google_calendar_credentials')
    op.drop_index('idx_credentials_active', table_name='google_calendar_credentials')
    op.drop_table('google_calendar_credentials')
    op.drop_index(op.f('ix_clinic_usage_clinic_id'), table_name='clinic_usage')
    op.drop_index(op.f('ix_clinic_usage_billing_period_start'), table_name='clinic_usage')
    op.drop_index('idx_clinic_usage_period', table_name='clinic_usage')
    op.drop_index('idx_clinic_usage_current', table_name='clinic_usage')
    op.drop_table('clinic_usage')
    op.drop_index(op.f('ix_clinic_licenses_clinic_id'), table_name='clinic_licenses')
    op.drop_index('idx_license_status', table_name='clinic_licenses')
    op.drop_index('idx_license_current_usage', table_name='clinic_licenses')
    op.drop_index('idx_license_billing_cycle', table_name='clinic_licenses')
    op.drop_table('clinic_licenses')
    op.drop_index('idx_call_queues_active', table_name='call_queues', postgresql_where=sa.text("is_deleted = 'no' AND is_active = true"))
    op.drop_table('call_queues')
    op.drop_table('appointment_blocks')
    op.drop_table('system_config')
    op.drop_table('providers')
    op.drop_index('idx_patients_phone_token', table_name='patients')
    op.drop_index('idx_patients_email_token', table_name='patients')
    op.drop_index('idx_patients_address_token', table_name='patients')
    op.drop_table('patients')
    op.drop_table('mappings')
    op.drop_table('clinics')
    op.drop_index('idx_caller_types_priority', table_name='caller_types')
    op.drop_index('idx_caller_types_active', table_name='caller_types', postgresql_where=sa.text("is_deleted = 'no' AND is_active = true"))
    op.drop_table('caller_types')
    op.drop_index('idx_audit_logs_user_date', table_name='audit_logs')
    op.drop_index('idx_audit_logs_table_date', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action_date', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
